import type { FlashCard } from "../../types";

export const symboler: FlashCard[] = [
  {
    id: "symboler-1",
    question:
      "Vad heter publikationen där alla sjökortssymboler finns redovisade?",
    questionQuiz:
      "I vilken publikation hittar du förklaringar till alla sjökortssymboler?",
    answer: "Kort 1.",
    options: [
      "Sjökortsboken.",
      "Kort 1.",
      "Navigationsguiden.",
      "Sjöregler 2020.",
    ],
    correctOptionIndex: 1,
  },

  {
    id: "symboler-2",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz:
      "Vad anger denna djupmarkering i sjökortet?",
    answer: "Att vattendjupet är 9 meter och 7 decimeter.",
    imageKey: "symboler_02_ver02",
    options: [
      "9,0 meter.",
      "9 meter och 7 decimeter.",
      "97 meter.",
      "7 meter och 9 decimeter.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-3",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad representerar denna brosymbol?",
    answer: "Fast bro med segelfri höjd i meter.",
    imageKey: "symboler_03_ver02",
    options: [
      "Öppningsbar bro.",
      "Fast bro med segelfri bredd i meter.",
      "Fast bro med segelfri höjd i meter.",
      "Sluss med 20 meters höjdskillnad",
    ],
    correctOptionIndex: 2,
  },
  {
    id: "symboler-4",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna brosymbol?",
    answer: "Öppningsbar bro.",
    imageKey: "symboler_04_ver02",
    options: [
      "Fast bro.",
      "Öppningsbar bro.",
      "Sluss.",
      "Vägport.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-5",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad markerar denna symbol i vattnet?",
    answer: "Bränning (grund, grynna).",
    imageKey: "symboler_05_ver02",
    options: [
      "Djupgrop.",
      "Bränning (grund).",
      "Sandbank.",
      "Ankringsplats.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-6",
    question: "Vad kallas dessa symboler på sjökortet?",
    questionQuiz: "Vad kallas linjer som visar samma djup?",
    answer: "Djupkurvor.",
    imageKey: "symboler_06_ver02",
    options: [
      "Farledslinjer.",
      "Djupkurvor.",
      "Bäringslinjer.",
      "Strömlinjer.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-7",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna strandlinjesymbol?",
    answer: "Ej kartlagd strandlinje.",
    imageKey: "symboler_07_ver02",
    options: [
      "Kartlagd strandlinje.",
      "Brygga.",
      "Ej kartlagd strandlinje.",
      "Sandstrand.",
    ],
    correctOptionIndex: 2,
  },
  {
    id: "symboler-8",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna pil i farleden?",
    answer: "Farledspil.",
    imageKey: "symboler_08_ver02",
    options: [
      "Strömriktning.",
      "Farledspil.",
      "Vindriktning.",
      "Pejllinje.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-9",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad betyder denna farledsmarkering?",
    answer: "Farled som ligger på en enslinje.",
    imageKey: "symboler_09_ver02",
    options: [
      "Farled med utprickning.",
      "Enslinje.",
      "Farled på enslinje.",
      "Alternativ farled.",
    ],
    correctOptionIndex: 2,
  },
  {
    id: "symboler-10",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad markerar denna farled?",
    answer: "Farled med flytande utprickning.",
    imageKey: "symboler_10_ver02",
    options: [
      "Farled utan märken.",
      "Farled med fasta märken.",
      "Farled med flytande utprickning.",
      "Djupgräns.",
    ],
    correctOptionIndex: 2,
  },
  {
    id: "symboler-11",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna anläggning i vattnet?",
    answer: "Fiskodling.",
    imageKey: "symboler_11_ver02",
    options: [
      "Hamnområde.",
      "Fiskodling.",
      "Undervattenskabel.",
      "Naturreservat.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-12",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad representerar denna landbaserade symbol?",
    answer: "Kyrka (kyrktorn).",
    imageKey: "symboler_12_ver02",
    options: [
      "Fyr.",
      "Kyrka (kyrktorn).",
      "Vattentorn.",
      "Radiomast.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-13",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad markerar detta skyddsområde?",
    answer: "Fågelskyddsområde.",
    imageKey: "symboler_13_ver02",
    options: [
      "Naturhamn.",
      "Fågelskyddsområde.",
      "Militärt område.",
      "Fiskeområde.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-14",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna linje i kanten av sjökortet?",
    answer: "Sjökortsgräns till annat sjökort.",
    imageKey: "symboler_14_ver02",
    options: [
      "Djupgräns.",
      "Sjökortsgräns.",
      "Terränggräns.",
      "Farledsgräns.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-15",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna symbol i en kanal?",
    answer: "Sluss.",
    imageKey: "symboler_15_ver02",
    options: [
      "Bro.",
      "Sluss.",
      "Färjeläge.",
      "Hamnbassäng.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-16",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna strandlinje?",
    answer: "Kartlagd strandlinje.",
    imageKey: "symboler_16_ver02",
    options: [
      "Ej kartlagd strandlinje.",
      "Kartlagd strandlinje.",
      "Strand med sand.",
      "Kaj.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-17",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad markerar denna symbol under vattenytan?",
    answer: "Undervattenssten.",
    imageKey: "symboler_17_ver02",
    options: [
      "Sandbank.",
      "Undervattenssten.",
      "Vrak.",
      "Djuphåla.",
    ],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-18",
    question: "Vad betyder denna symbol på sjökortet?",
    questionQuiz: "Vad visar denna linje på sjökortet?",
    answer: "Undervattenskabel.",
    imageKey: "symboler_18_ver02",
    options: [
      "Undervattenskabel.",
      "Gasledning.",
      "Strömriktning.",
      "Djupkurva.",
    ],
    correctOptionIndex: 0,
  },

  {
    id: "symboler-19",
    question: 'Vilken färg menas med "W" på ett sjökort?',
    questionQuiz: 'Vad betyder färgkoden "W" i fyrkaraktärer?',
    answer: "Vit (White).",
    options: ["Vit.", "Gul.", "Blå.", "Grön."],
    correctOptionIndex: 0,
  },
  {
    id: "symboler-20",
    question: 'Vilken färg menas med "Y" på ett sjökort?',
    questionQuiz: 'Vad står "Y" för i färgförkortningar?',
    answer: "Gul (Yellow).",
    options: ["Vit.", "Röd.", "Gul.", "Grön."],
    correctOptionIndex: 2,
  },
  {
    id: "symboler-21",
    question: 'Vilken färg menas med "B" på ett sjökort?',
    questionQuiz: 'Vad betyder bokstaven "B" i sjökortets färgkod?',
    answer: "Svart (Black).",
    options: ["Blå.", "Brun.", "Svart.", "Vit."],
    correctOptionIndex: 2,
  },
  {
    id: "symboler-22",
    question: 'Vad består botten av om den är beskriven med "M"?',
    questionQuiz: 'Vad betyder bottentypen "M" i sjökort?',
    answer: "Gyttja (Mud).",
    options: ["Sand.", "Gyttja.", "Sten.", "Grus."],
    correctOptionIndex: 1,
  },
  {
    id: "symboler-23",
    question: 'Vad består botten av om den är beskriven med "S"?',
    questionQuiz: 'Vad betyder bottentypen "S" i sjökort?',
    answer: "Sand (Sand).",
    options: ["Sten.", "Silt.", "Sand.", "Skal."],
    correctOptionIndex: 2,
  },
];
