
export const cardImages: Record<string, any> = {
 
"flytande_sjomarken_04": require("../../assets/cards/sjokortet/sjokortet_sjomarken/flytande_sjomarken_04.jpg"),
"flytande_sjomarken_05": require("../../assets/cards/sjokortet/sjokortet_sjomarken/flytande_sjomarken_05.jpg"),
"flytande_sjomarken_06": require("../../assets/cards/sjokortet/sjokortet_sjomarken/flytande_sjomarken_06.jpg"),
"flytande_sjomarken_07": require("../../assets/cards/sjokortet/sjokortet_sjomarken/flytande_sjomarken_07.jpg"),
"flytande_sjomarken_08": require("../../assets/cards/sjokortet/sjokortet_sjomarken/flytande_sjomarken_08.jpg"),
"flytande_sjomarken_09": require("../../assets/cards/sjokortet/sjokortet_sjomarken/flytande_sjomarken_09.jpg"),

"fasta_sjomarken_05": require("../../assets/cards/sjokortet/sjokortet_sjomarken/fasta_sjomarken_05.jpg"),

"farledsnavigation_02": require("../../assets/cards/praktiskt_navigation/farledsnavigation_02.jpg"),

"knopar_och_linor_06": require("../../assets/cards/sjomanskap/knopar_och_linor_06.jpg"),
"knopar_och_linor_07": require("../../assets/cards/sjomanskap/knopar_och_linor_07.jpg"),
"knopar_och_linor_08": require("../../assets/cards/sjomanskap/knopar_och_linor_08.jpg"),
"knopar_och_linor_09": require("../../assets/cards/sjomanskap/knopar_och_linor_09.jpg"),

"symboler_02": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_02.jpg"),
"symboler_03": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_03.jpg"),
"symboler_04": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_04.jpg"),
"symboler_05": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_05.jpg"),
"symboler_06": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_06.jpg"),
"symboler_07": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_07.jpg"),
"symboler_08": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_08.jpg"),
"symboler_09": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_09.jpg"),
"symboler_10": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_10.jpg"),
"symboler_11": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_11.jpg"),
"symboler_12": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_12.jpg"),
"symboler_13": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_13.jpg"),
"symboler_14": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_14.jpg"),
"symboler_15": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_15.jpg"),
"symboler_16": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_16.jpg"),
"symboler_17": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_17.jpg"),
"symboler_18": require("../../assets/cards/sjokortet/sjokortet_sjomarken/symboler_18.jpg"),

"bonus_dagersignaler_01": require("../../assets/cards/bonus/bonus_dagersignaler_01.jpg"),
"bonus_dagersignaler_02": require("../../assets/cards/bonus/bonus_dagersignaler_02.jpg"),
"bonus_dagersignaler_03": require("../../assets/cards/bonus/bonus_dagersignaler_03.jpg"),
"bonus_dagersignaler_04": require("../../assets/cards/bonus/bonus_dagersignaler_04.jpg"),
"bonus_dagersignaler_05": require("../../assets/cards/bonus/bonus_dagersignaler_05.jpg"),
"bonus_dagersignaler_06": require("../../assets/cards/bonus/bonus_dagersignaler_06.jpg"),
"bonus_dagersignaler_07": require("../../assets/cards/bonus/bonus_dagersignaler_07.jpg"),
"bonus_dagersignaler_08": require("../../assets/cards/bonus/bonus_dagersignaler_08.jpg"),
"bonus_dagersignaler_09": require("../../assets/cards/bonus/bonus_dagersignaler_09.jpg"),

"bonus_flaggor_01": require("../../assets/cards/bonus/bonus_flaggor_01.jpg"),
"bonus_flaggor_02": require("../../assets/cards/bonus/bonus_flaggor_02.jpg"),
"bonus_flaggor_03": require("../../assets/cards/bonus/bonus_flaggor_03.jpg"),
"bonus_flaggor_04": require("../../assets/cards/bonus/bonus_flaggor_04.jpg"),
"bonus_flaggor_05": require("../../assets/cards/bonus/bonus_flaggor_05.jpg"),
"bonus_flaggor_06": require("../../assets/cards/bonus/bonus_flaggor_06.jpg"),
"bonus_flaggor_07": require("../../assets/cards/bonus/bonus_flaggor_07.jpg"),

"bonus_fortojningslinor_01": require("../../assets/cards/bonus/bonus_fortojningslinor_01.jpg"),
"bonus_fortojningslinor_02": require("../../assets/cards/bonus/bonus_fortojningslinor_02.jpg"),
"bonus_fortojningslinor_03": require("../../assets/cards/bonus/bonus_fortojningslinor_03.jpg"),
"bonus_fortojningslinor_04": require("../../assets/cards/bonus/bonus_fortojningslinor_04.jpg"),
"bonus_fortojningslinor_05": require("../../assets/cards/bonus/bonus_fortojningslinor_05.jpg"),
"bonus_fortojningslinor_06": require("../../assets/cards/bonus/bonus_fortojningslinor_06.jpg"),

"bonus_kardinal_01": require("../../assets/cards/bonus/bonus_kardinal_01.jpg"),
"bonus_kardinal_02": require("../../assets/cards/bonus/bonus_kardinal_02.jpg"),
"bonus_kardinal_03": require("../../assets/cards/bonus/bonus_kardinal_03.jpg"),
"bonus_kardinal_04": require("../../assets/cards/bonus/bonus_kardinal_04.jpg"),

"bonus_lanternor_01": require("../../assets/cards/bonus/bonus_lanternor_01.jpg"),
"bonus_lanternor_02": require("../../assets/cards/bonus/bonus_lanternor_02.jpg"),
"bonus_lanternor_03": require("../../assets/cards/bonus/bonus_lanternor_03.jpg"),
"bonus_lanternor_04": require("../../assets/cards/bonus/bonus_lanternor_04.jpg"),
"bonus_lanternor_05": require("../../assets/cards/bonus/bonus_lanternor_05.jpg"),
"bonus_lanternor_06": require("../../assets/cards/bonus/bonus_lanternor_06.jpg"),
"bonus_lanternor_07": require("../../assets/cards/bonus/bonus_lanternor_07.jpg"),
"bonus_lanternor_08": require("../../assets/cards/bonus/bonus_lanternor_08.jpg"),
"bonus_lanternor_09": require("../../assets/cards/bonus/bonus_lanternor_09.jpg"),
"bonus_lanternor_10": require("../../assets/cards/bonus/bonus_lanternor_10.jpg"),
"bonus_lanternor_11": require("../../assets/cards/bonus/bonus_lanternor_11.jpg"),
"bonus_lanternor_12": require("../../assets/cards/bonus/bonus_lanternor_12.jpg"),
"bonus_lanternor_13": require("../../assets/cards/bonus/bonus_lanternor_13.jpg"),
"bonus_lanternor_14": require("../../assets/cards/bonus/bonus_lanternor_14.jpg"),
"bonus_lanternor_15": require("../../assets/cards/bonus/bonus_lanternor_15.jpg"),

"bonus_ljudsignaler_01": require("../../assets/cards/bonus/bonus_ljudsignaler_01.jpg"),
"bonus_ljudsignaler_02": require("../../assets/cards/bonus/bonus_ljudsignaler_02.jpg"),
"bonus_ljudsignaler_03": require("../../assets/cards/bonus/bonus_ljudsignaler_03.jpg"),
"bonus_ljudsignaler_04": require("../../assets/cards/bonus/bonus_ljudsignaler_04.jpg"),
"bonus_ljudsignaler_05": require("../../assets/cards/bonus/bonus_ljudsignaler_05.jpg"),
"bonus_ljudsignaler_06": require("../../assets/cards/bonus/bonus_ljudsignaler_06.jpg"),
"bonus_ljudsignaler_07": require("../../assets/cards/bonus/bonus_ljudsignaler_07.jpg"),
"bonus_ljudsignaler_08": require("../../assets/cards/bonus/bonus_ljudsignaler_08.jpg"),
"bonus_ljudsignaler_09": require("../../assets/cards/bonus/bonus_ljudsignaler_09.jpg"),
"bonus_ljudsignaler_10": require("../../assets/cards/bonus/bonus_ljudsignaler_10.jpg"),
"bonus_ljudsignaler_11": require("../../assets/cards/bonus/bonus_ljudsignaler_11.jpg"),
"bonus_ljudsignaler_12": require("../../assets/cards/bonus/bonus_ljudsignaler_12.jpg"),


"bonus_sjomarken_01": require("../../assets/cards/bonus/bonus_sjomarken_01.jpg"),
"bonus_sjomarken_02": require("../../assets/cards/bonus/bonus_sjomarken_02.jpg"),
"bonus_sjomarken_03": require("../../assets/cards/bonus/bonus_sjomarken_03.jpg"),
"bonus_sjomarken_04": require("../../assets/cards/bonus/bonus_sjomarken_04.jpg"),
"bonus_sjomarken_05": require("../../assets/cards/bonus/bonus_sjomarken_05.jpg"),
"bonus_sjomarken_06": require("../../assets/cards/bonus/bonus_sjomarken_06.jpg"),
"bonus_sjomarken_07": require("../../assets/cards/bonus/bonus_sjomarken_07.jpg"),
"bonus_sjomarken_08": require("../../assets/cards/bonus/bonus_sjomarken_08.jpg"),
"bonus_sjomarken_09": require("../../assets/cards/bonus/bonus_sjomarken_09.jpg"),
"bonus_sjomarken_10": require("../../assets/cards/bonus/bonus_sjomarken_10.jpg"),
"bonus_sjomarken_11": require("../../assets/cards/bonus/bonus_sjomarken_11.jpg"),
"bonus_sjomarken_12": require("../../assets/cards/bonus/bonus_sjomarken_12.jpg"),
"bonus_sjomarken_13": require("../../assets/cards/bonus/bonus_sjomarken_13.jpg"),
"bonus_sjomarken_14": require("../../assets/cards/bonus/bonus_sjomarken_14.jpg"),
"bonus_sjomarken_15": require("../../assets/cards/bonus/bonus_sjomarken_15.jpg"),
"bonus_sjomarken_16": require("../../assets/cards/bonus/bonus_sjomarken_16.jpg"),
"bonus_sjomarken_17": require("../../assets/cards/bonus/bonus_sjomarken_17.jpg"),
"bonus_sjomarken_18": require("../../assets/cards/bonus/bonus_sjomarken_18.jpg"),
"bonus_sjomarken_19": require("../../assets/cards/bonus/bonus_sjomarken_19.jpg"),
"bonus_sjomarken_20": require("../../assets/cards/bonus/bonus_sjomarken_20.jpg"),
"bonus_sjomarken_21": require("../../assets/cards/bonus/bonus_sjomarken_21.jpg"),
"bonus_sjomarken_22": require("../../assets/cards/bonus/bonus_sjomarken_22.jpg"),
};
