
export const cardImages: Record<string, any> = {
  "utmarkning_av_grund_prickar_och_bojar_4_4_a": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_4_a.png"),
  "utmarkning_av_grund_prickar_och_bojar_4_4_d": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_4_d.png"),
  "utmarkning_av_grund_prickar_och_bojar_4_5": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_5.png"),
  "utmarkning_av_grund_prickar_och_bojar_4_6": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_6.png"),
   "praktisk_skargardsnavigering_5_1_facit": require("../../assets/cards/praktisk_skargardsnavigering_5_1_facit.png"),
    "praktisk_skargardsnavigering_5_1": require("../../assets/cards/praktisk_skargardsnavigering_5_1.png"),
    "sjokortet_1_13": require("../../assets/cards/sjokortet_1_13.png"),
"kompassen_3_7": require("../../assets/cards/kompassen_3_7.png"),
"kompassen_3_8": require("../../assets/cards/kompassen_3_8.png"),
"sjomanskap_9_1": require("../../assets/cards/sjomanskap_9_1.png"),
"flytande_sjomarken_04": require("../../assets/cards/flytande_sjomarken_04.jpg"),
"flytande_sjomarken_05": require("../../assets/cards/flytande_sjomarken_05.jpg"),
"flytande_sjomarken_06": require("../../assets/cards/flytande_sjomarken_06.jpg"),
"flytande_sjomarken_07": require("../../assets/cards/flytande_sjomarken_07.jpg"),
"flytande_sjomarken_08": require("../../assets/cards/flytande_sjomarken_08.jpg"),
"flytande_sjomarken_09": require("../../assets/cards/flytande_sjomarken_09.jpg"),
"flytande_sjomarken_04_ver02": require("../../assets/cards/flytande_sjomarken_04_ver02.jpg"),
"flytande_sjomarken_05_ver02": require("../../assets/cards/flytande_sjomarken_05_ver02.jpg"),
"flytande_sjomarken_06_ver02": require("../../assets/cards/flytande_sjomarken_06_ver02.jpg"),
"flytande_sjomarken_07_ver02": require("../../assets/cards/flytande_sjomarken_07_ver02.jpg"),
"flytande_sjomarken_08_ver02": require("../../assets/cards/flytande_sjomarken_08_ver02.jpg"),
"flytande_sjomarken_09_ver02": require("../../assets/cards/flytande_sjomarken_09_ver02.jpg"),


"fasta_sjomarken_05_facit": require("../../assets/cards/fasta_sjomarken_05_facit.jpg"),
"fasta_sjomarken_05_facit_ver02": require("../../assets/cards/fasta_sjomarken_05_facit_ver02.jpg"),
"mata_kort_distans_01": require("../../assets/cards/mata_kort_distans_01.jpg"),
"mata_kort_distans_01_ver02": require("../../assets/cards/mata_kort_distans_01_ver02.jpg"),
"farledsnavigation_02": require("../../assets/cards/farledsnavigation_02.jpg"),
"farledsnavigation_02_ver02": require("../../assets/cards/farledsnavigation_02_ver02.jpg"),
"segelbatar_09": require("../../assets/cards/segelbatar_09.jpg"),

"knopar_och_linor_06": require("../../assets/cards/knopar_och_linor_06.jpg"),
"knopar_och_linor_07": require("../../assets/cards/knopar_och_linor_07.jpg"),
"knopar_och_linor_08": require("../../assets/cards/knopar_och_linor_08.jpg"),
"knopar_och_linor_09": require("../../assets/cards/knopar_och_linor_09.jpg"),
"knopar_och_linor_10": require("../../assets/cards/knopar_och_linor_10.jpg"),
"knopar_och_linor_06_ver02": require("../../assets/cards/knopar_och_linor_06_ver02.jpg"),
"knopar_och_linor_07_ver02": require("../../assets/cards/knopar_och_linor_07_ver02.jpg"),
"knopar_och_linor_08_ver02": require("../../assets/cards/knopar_och_linor_08_ver02.jpg"),
"knopar_och_linor_09_ver02": require("../../assets/cards/knopar_och_linor_09_ver02.jpg"),

"symboler_02_ver02": require("../../assets/cards/symboler_02_ver02.jpg"),
"symboler_03_ver02": require("../../assets/cards/symboler_03_ver02.jpg"),
"symboler_04_ver02": require("../../assets/cards/symboler_04_ver02.jpg"),
"symboler_05_ver02": require("../../assets/cards/symboler_05_ver02.jpg"),
"symboler_06_ver02": require("../../assets/cards/symboler_06_ver02.jpg"),
"symboler_07_ver02": require("../../assets/cards/symboler_07_ver02.jpg"),
"symboler_08_ver02": require("../../assets/cards/symboler_08_ver02.jpg"),
"symboler_09_ver02": require("../../assets/cards/symboler_09_ver02.jpg"),
"symboler_10_ver02": require("../../assets/cards/symboler_10_ver02.jpg"),
"symboler_11_ver02": require("../../assets/cards/symboler_11_ver02.jpg"),
"symboler_12_ver02": require("../../assets/cards/symboler_12_ver02.jpg"),
"symboler_13_ver02": require("../../assets/cards/symboler_13_ver02.jpg"),
"symboler_14_ver02": require("../../assets/cards/symboler_14_ver02.jpg"),

"symboler_15_ver02": require("../../assets/cards/symboler_15_ver02.jpg"),
"symboler_16_ver02": require("../../assets/cards/symboler_16_ver02.jpg"),
"symboler_17_ver02": require("../../assets/cards/symboler_17_ver02.jpg"),
"symboler_18_ver02": require("../../assets/cards/symboler_18_ver02.jpg"),

"flagga_alfa": require("../../assets/cards/symboler_15_ver02.jpg"),
"flagga_oscar": require("../../assets/cards/symboler_16_ver02.jpg"),
"flagga_delta": require("../../assets/cards/symboler_17_ver02.jpg"),
"flagga_bravo": require("../../assets/cards/symboler_18_ver02.jpg"),

"bonus_dagersignaler_01": require("../../assets/cards/bonus_dagersignaler_01.jpg"),
"bonus_dagersignaler_02": require("../../assets/cards/bonus_dagersignaler_02.jpg"),
"bonus_dagersignaler_03": require("../../assets/cards/bonus_dagersignaler_03.jpg"),
"bonus_dagersignaler_04": require("../../assets/cards/bonus_dagersignaler_04.jpg"),
"bonus_dagersignaler_05": require("../../assets/cards/bonus_dagersignaler_05.jpg"),
"bonus_dagersignaler_06": require("../../assets/cards/bonus_dagersignaler_06.jpg"),
"bonus_dagersignaler_07": require("../../assets/cards/bonus_dagersignaler_07.jpg"),
"bonus_dagersignaler_08": require("../../assets/cards/bonus_dagersignaler_08.jpg"),
"bonus_dagersignaler_09": require("../../assets/cards/bonus_dagersignaler_09.jpg"),

"bonus_flaggor_01": require("../../assets/cards/bonus_flaggor_01.jpg"),
"bonus_flaggor_02": require("../../assets/cards/bonus_flaggor_02.jpg"),
"bonus_flaggor_03": require("../../assets/cards/bonus_flaggor_03.jpg"),
"bonus_flaggor_04": require("../../assets/cards/bonus_flaggor_04.jpg"),
"bonus_flaggor_05": require("../../assets/cards/bonus_flaggor_05.jpg"),
"bonus_flaggor_06": require("../../assets/cards/bonus_flaggor_06.jpg"),
"bonus_flaggor_07": require("../../assets/cards/bonus_flaggor_07.jpg"),

"bonus_fortojningslinor_01": require("../../assets/cards/bonus_fortojningslinor_01.jpg"),
"bonus_fortojningslinor_02": require("../../assets/cards/bonus_fortojningslinor_02.jpg"),
"bonus_fortojningslinor_03": require("../../assets/cards/bonus_fortojningslinor_03.jpg"),
"bonus_fortojningslinor_04": require("../../assets/cards/bonus_fortojningslinor_04.jpg"),
"bonus_fortojningslinor_05": require("../../assets/cards/bonus_fortojningslinor_05.jpg"),
"bonus_fortojningslinor_06": require("../../assets/cards/bonus_fortojningslinor_06.jpg"),

"bonus_kardinal_01": require("../../assets/cards/bonus_kardinal_01.jpg"),
"bonus_kardinal_02": require("../../assets/cards/bonus_kardinal_02.jpg"),
"bonus_kardinal_03": require("../../assets/cards/bonus_kardinal_03.jpg"),
"bonus_kardinal_04": require("../../assets/cards/bonus_kardinal_04.jpg"),

"bonus_lanternor_01": require("../../assets/cards/bonus_lanternor_01.jpg"),
"bonus_lanternor_02": require("../../assets/cards/bonus_lanternor_02.jpg"),
"bonus_lanternor_03": require("../../assets/cards/bonus_lanternor_03.jpg"),
"bonus_lanternor_04": require("../../assets/cards/bonus_lanternor_04.jpg"),
"bonus_lanternor_05": require("../../assets/cards/bonus_lanternor_05.jpg"),
"bonus_lanternor_06": require("../../assets/cards/bonus_lanternor_06.jpg"),
"bonus_lanternor_07": require("../../assets/cards/bonus_lanternor_07.jpg"),
"bonus_lanternor_08": require("../../assets/cards/bonus_lanternor_08.jpg"),
"bonus_lanternor_09": require("../../assets/cards/bonus_lanternor_09.jpg"),
"bonus_lanternor_10": require("../../assets/cards/bonus_lanternor_10.jpg"),
"bonus_lanternor_11": require("../../assets/cards/bonus_lanternor_11.jpg"),
"bonus_lanternor_12": require("../../assets/cards/bonus_lanternor_12.jpg"),
"bonus_lanternor_13": require("../../assets/cards/bonus_lanternor_13.jpg"),
"bonus_lanternor_14": require("../../assets/cards/bonus_lanternor_14.jpg"),
"bonus_lanternor_15": require("../../assets/cards/bonus_lanternor_15.jpg"),

"bonus_ljudsignaler_01": require("../../assets/cards/bonus_ljudsignaler_01.jpg"),
"bonus_ljudsignaler_02": require("../../assets/cards/bonus_ljudsignaler_02.jpg"),
"bonus_ljudsignaler_03": require("../../assets/cards/bonus_ljudsignaler_03.jpg"),
"bonus_ljudsignaler_04": require("../../assets/cards/bonus_ljudsignaler_04.jpg"),
"bonus_ljudsignaler_05": require("../../assets/cards/bonus_ljudsignaler_05.jpg"),
"bonus_ljudsignaler_06": require("../../assets/cards/bonus_ljudsignaler_06.jpg"),
"bonus_ljudsignaler_07": require("../../assets/cards/bonus_ljudsignaler_07.jpg"),
"bonus_ljudsignaler_08": require("../../assets/cards/bonus_ljudsignaler_08.jpg"),
"bonus_ljudsignaler_09": require("../../assets/cards/bonus_ljudsignaler_09.jpg"),
"bonus_ljudsignaler_10": require("../../assets/cards/bonus_ljudsignaler_10.jpg"),
"bonus_ljudsignaler_11": require("../../assets/cards/bonus_ljudsignaler_11.jpg"),
"bonus_ljudsignaler_12": require("../../assets/cards/bonus_ljudsignaler_12.jpg"),


"bonus_sjomarken_01": require("../../assets/cards/bonus_sjomarken_01.jpg"),
"bonus_sjomarken_02": require("../../assets/cards/bonus_sjomarken_02.jpg"),
"bonus_sjomarken_03": require("../../assets/cards/bonus_sjomarken_03.jpg"),
"bonus_sjomarken_04": require("../../assets/cards/bonus_sjomarken_04.jpg"),
"bonus_sjomarken_05": require("../../assets/cards/bonus_sjomarken_05.jpg"),
"bonus_sjomarken_06": require("../../assets/cards/bonus_sjomarken_06.jpg"),
"bonus_sjomarken_07": require("../../assets/cards/bonus_sjomarken_07.jpg"),
"bonus_sjomarken_08": require("../../assets/cards/bonus_sjomarken_08.jpg"),
"bonus_sjomarken_09": require("../../assets/cards/bonus_sjomarken_09.jpg"),
"bonus_sjomarken_10": require("../../assets/cards/bonus_sjomarken_10.jpg"),
"bonus_sjomarken_11": require("../../assets/cards/bonus_sjomarken_11.jpg"),
"bonus_sjomarken_12": require("../../assets/cards/bonus_sjomarken_12.jpg"),
"bonus_sjomarken_13": require("../../assets/cards/bonus_sjomarken_13.jpg"),
"bonus_sjomarken_14": require("../../assets/cards/bonus_sjomarken_14.jpg"),
"bonus_sjomarken_15": require("../../assets/cards/bonus_sjomarken_15.jpg"),
"bonus_sjomarken_16": require("../../assets/cards/bonus_sjomarken_16.jpg"),
"bonus_sjomarken_17": require("../../assets/cards/bonus_sjomarken_17.jpg"),
"bonus_sjomarken_18": require("../../assets/cards/bonus_sjomarken_18.jpg"),
"bonus_sjomarken_19": require("../../assets/cards/bonus_sjomarken_19.jpg"),
"bonus_sjomarken_20": require("../../assets/cards/bonus_sjomarken_20.jpg"),
"bonus_sjomarken_21": require("../../assets/cards/bonus_sjomarken_21.jpg"),
"bonus_sjomarken_22": require("../../assets/cards/bonus_sjomarken_22.jpg"),
};
