export const cardImages: Record<string, any> = {
  "utmarkning_av_grund_prickar_och_bojar_4_4_a": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_4_a.png"),
  "utmarkning_av_grund_prickar_och_bojar_4_4_d": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_4_d.png"),
  "utmarkning_av_grund_prickar_och_bojar_4_5": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_5.png"),
  "utmarkning_av_grund_prickar_och_bojar_4_6": require("../../assets/cards/utmarkning_av_grund_prickar_och_bojar_4_6.png"),
   "praktisk_skargardsnavigering_5_1_facit": require("../../assets/cards/praktisk_skargardsnavigering_5_1_facit.png"),
    "praktisk_skargardsnavigering_5_1": require("../../assets/cards/praktisk_skargardsnavigering_5_1.png"),
    "sjokortet_1_13": require("../../assets/cards/sjokortet_1_13.png"),
"kompassen_3_7": require("../../assets/cards/kompassen_3_7.png"),
"kompassen_3_8": require("../../assets/cards/kompassen_3_8.png"),
"sjomanskap_9_1": require("../../assets/cards/sjomanskap_9_1.png"),
"flytande_sjomarken_04": require("../../assets/cards/flytande_sjomarken_04.jpg"),
"flytande_sjomarken_05": require("../../assets/cards/flytande_sjomarken_05.jpg"),
"flytande_sjomarken_06": require("../../assets/cards/flytande_sjomarken_06.jpg"),
"flytande_sjomarken_07": require("../../assets/cards/flytande_sjomarken_07.jpg"),
"flytande_sjomarken_08": require("../../assets/cards/flytande_sjomarken_08.jpg"),
"flytande_sjomarken_09": require("../../assets/cards/flytande_sjomarken_09.jpg"),
"flytande_sjomarken_04_ver02": require("../../assets/cards/flytande_sjomarken_04_ver02.jpg"),
"flytande_sjomarken_05_ver02": require("../../assets/cards/flytande_sjomarken_05_ver02.jpg"),
"flytande_sjomarken_06_ver02": require("../../assets/cards/flytande_sjomarken_06_ver02.jpg"),
"flytande_sjomarken_07_ver02": require("../../assets/cards/flytande_sjomarken_07_ver02.jpg"),
"flytande_sjomarken_08_ver02": require("../../assets/cards/flytande_sjomarken_08_ver02.jpg"),
"flytande_sjomarken_09_ver02": require("../../assets/cards/flytande_sjomarken_09_ver02.jpg"),



"fasta_sjomarken_05_facit": require("../../assets/cards/fasta_sjomarken_05_facit.jpg"),
"fasta_sjomarken_05_facit_ver02": require("../../assets/cards/fasta_sjomarken_05_facit_ver02.jpg"),
"mata_kort_distans_01": require("../../assets/cards/mata_kort_distans_01.jpg"),
"mata_kort_distans_01_ver02": require("../../assets/cards/mata_kort_distans_01_ver02.jpg"),
"farledsnavigation_02": require("../../assets/cards/farledsnavigation_02.jpg"),
"farledsnavigation_02_ver02": require("../../assets/cards/farledsnavigation_02_ver02.jpg"),
"segelbatar_09": require("../../assets/cards/segelbatar_09.jpg"),
"knopar_och_linor_06": require("../../assets/cards/knopar_och_linor_06.jpg"),
"knopar_och_linor_07": require("../../assets/cards/knopar_och_linor_07.jpg"),
"knopar_och_linor_08": require("../../assets/cards/knopar_och_linor_08.jpg"),
"knopar_och_linor_09": require("../../assets/cards/knopar_och_linor_09.jpg"),
"knopar_och_linor_10": require("../../assets/cards/knopar_och_linor_10.jpg"),
"knopar_och_linor_06_ver02": require("../../assets/cards/knopar_och_linor_06_ver02.jpg"),
"knopar_och_linor_07_ver02": require("../../assets/cards/knopar_och_linor_07_ver02.jpg"),
"knopar_och_linor_08_ver02": require("../../assets/cards/knopar_och_linor_08_ver02.jpg"),
"knopar_och_linor_09_ver02": require("../../assets/cards/knopar_och_linor_09_ver02.jpg"),

"symboler_02_ver02": require("../../assets/cards/symboler_02_ver02.jpg"),
"symboler_03_ver02": require("../../assets/cards/symboler_03_ver02.jpg"),
"symboler_04_ver02": require("../../assets/cards/symboler_04_ver02.jpg"),
"symboler_05_ver02": require("../../assets/cards/symboler_05_ver02.jpg"),
"symboler_06_ver02": require("../../assets/cards/symboler_06_ver02.jpg"),
"symboler_07_ver02": require("../../assets/cards/symboler_07_ver02.jpg"),
"symboler_08_ver02": require("../../assets/cards/symboler_08_ver02.jpg"),
"symboler_09_ver02": require("../../assets/cards/symboler_09_ver02.jpg"),
"symboler_10_ver02": require("../../assets/cards/symboler_10_ver02.jpg"),
"symboler_11_ver02": require("../../assets/cards/symboler_11_ver02.jpg"),
"symboler_12_ver02": require("../../assets/cards/symboler_12_ver02.jpg"),
"symboler_13_ver02": require("../../assets/cards/symboler_13_ver02.jpg"),
"symboler_14_ver02": require("../../assets/cards/symboler_14_ver02.jpg"),

"symboler_15_ver02": require("../../assets/cards/symboler_15_ver02.jpg"),
"symboler_16_ver02": require("../../assets/cards/symboler_16_ver02.jpg"),
"symboler_17_ver02": require("../../assets/cards/symboler_17_ver02.jpg"),
"symboler_18_ver02": require("../../assets/cards/symboler_18_ver02.jpg"),

"flagga_alfa": require("../../assets/cards/symboler_15_ver02.jpg"),
"flagga_oscar": require("../../assets/cards/symboler_16_ver02.jpg"),
"flagga_delta": require("../../assets/cards/symboler_17_ver02.jpg"),
"flagga_bravo": require("../../assets/cards/symboler_18_ver02.jpg"),

};
