import type { Chapter } from "../../constants/flashcards/types";

export const courseChapters: Chapter[] = [
{
      id: "sjokortet",
      title: "Kartunderlag & Koordinater",
      titleShort: "Kartor",
      deckId: "sjokortet",
      children: [
        { id: "sjokortstyper", title: "Sjökortstyper", deckId: "sjokortstyper" },
        { id: "papperssjokort", title: "Papperssjökort", deckId: "papperssjokort" },
        { id: "elektroniska_sjokort", title: "Elektroniska sjökort", deckId: "elektroniska_sjokort" },
        { id: "tillforlitlighet", title: "Tillförlitlighet", deckId: "tillforlitlighet" },
        { id: "longitud_latitud", title: "Longitud och latitud", deckId: "longitud_latitud" },
      
        {
      id: "sjokortet_quiz",
      title: "Kapitelquiz",
      quizId: "sjokortet_quiz",
      type: "quiz",
    },
      ],
    },

   
    {
      id: "sjokortet_sjomarken",
      title: "Sjövägsmärken & Markeringar",
      titleShort: "Märken",
      children: [
        { id: "flytande_sjomarken", title: "Flytande sjömärken", deckId: "flytande_sjomarken" },
        { id: "fasta_sjomarken", title: "Fasta sjömärken", deckId: "fasta_sjomarken" },
          { id: "symboler", title: "Symboler", deckId: "symboler" },
        {
      id: "sjokortet_sjomarken_quiz",
      title: "Kapitelquiz",
      quizId: "sjokortet_sjomarken_quiz",
      type: "quiz",
    },
      ],
    },

    {
      id: "sjokortsarbete",
      title: "Praktiskt Arbete i Sjökort",
      titleShort: "Mätning",
      children: [
        { id: "mata_kort_distans", title: "Mäta kort distans", deckId: "mata_kort_distans" },
        { id: "mata_langre_distans", title: "Mäta längre distans", deckId: "mata_langre_distans" },
        { id: "ta_fram_position", title: "Ta fram position", deckId: "ta_fram_position" },
        { id: "markera_position", title: "Markera position", deckId: "markera_position" },
        { id: "lagga_ut_kurs", title: "Lägga ut kurs", deckId: "lagga_ut_kurs" },
        { id: "mata_upp_kurs", title: "Mäta upp kurs", deckId: "mata_upp_kurs" },
        { id: "krysspejling", title: "Krysspejling", deckId: "krysspejling" },
         {
      id: "sjokortsarbete_quiz",
      title: "Kapitelquiz",
      quizId: "sjokortsarbete_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "navigationsteori",
      title: "Navigationsprinciper",
      titleShort: "Navigering",
      children: [
        { id: "vaderstreck", title: "Väderstreck", deckId: "vaderstreck" },
        { id: "navigationsbestick", title: "Navigationsbestick", deckId: "navigationsbestick" },
        { id: "kurs_baring_riktning", title: "Kurs, bäring och riktning", deckId: "kurs_baring_riktning" },
        { id: "position", title: "Position", deckId: "position" },
        { id: "distans", title: "Distans", deckId: "distans" },
        { id: "berakningar", title: "Beräkningar", deckId: "berakningar" },
        { id: "deviation_missvisning", title: "Deviation & missvisning", deckId: "deviation_missvisning" },
        { id: "avdrift_strom", title: "Avdrift & ström", deckId: "avdrift_strom" },
        { id: "ratta_satta_kurs", title: "Rätta & sätta kurs", deckId: "ratta_satta_kurs" },
         {
      id: "navigationsteori_quiz",
      title: "Kapitelquiz",
      quizId: "navigationsteori_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "praktisk_navigation",
      title: "Navigering i Praktiken",
      titleShort: "Rutter",
      children: [
        { id: "planering", title: "Planering", deckId: "planering" },
        { id: "farledsnavigation", title: "Farledsnavigation", deckId: "farledsnavigation" },
        { id: "optisk_navigation", title: "Optisk navigation", deckId: "optisk_navigation" },
        { id: "instrumentnavigation", title: "Instrumentnavigation", deckId: "instrumentnavigation" },
        { id: "navigatornavigation", title: "Navigatornavigation", deckId: "navigatornavigation" },
        {
      id: "praktisk_navigation_quiz",
      title: "Kapitelquiz",
      quizId: "praktisk_navigationi_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "vajningsregler",
      title: "Trafikregler till Sjöss",
      titleShort: "Regler",
      children: [
        { id: "vajningsregler_inledning", title: "Inledning", deckId: "vajningsregler_inledning" },
        { id: "vajningsregler_smabatar", title: "Småbåtar", deckId: "vajningsregler_smabatar" },
        { id: "vajningsregler_segelbatar", title: "Segelbåtar", deckId: "vajningsregler_segelbatar" },
        { id: "vajningsregler_motorbatar", title: "Motorbåtar", deckId: "vajningsregler_motorbatar" },
        { id: "vajningsregler_fartyg", title: "Fartyg", deckId: "vajningsregler_fartyg" },
        {
      id: "vajningsregler_quiz",
      title: "Kapitelquiz",
      quizId: "vajningsregler_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "lanternor",
      title: "Navigationsljus",
      titleShort: "Ljus",
      children: [
        { id: "lanternor_inledning", title: "Inledning", deckId: "lanternor_inledning" },
        { id: "lanternor_smabatar", title: "Småbåtar", deckId: "lanternor_smabatar" },
        { id: "lanternor_segelbatar", title: "Segelbåtar", deckId: "lanternor_segelbatar" },
        { id: "lanternor_motorbatar", title: "Motorbåtar", deckId: "lanternor_motorbatar" },
        { id: "lanternor_fartyg", title: "Fartyg", deckId: "lanternor_fartyg" },
        { id: "lanternor_sarskilda_fartyg", title: "Särskilda fartyg", deckId: "lanternor_sarskilda_fartyg" },
         {
      id: "lanternor_quiz",
      title: "Kapitelquiz",
      quizId: "lanternor_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "manovrering",
      title: "Båtens Rörelser & Kontroll",
      titleShort: "Styrning",
      children: [
        { id: "manovrering_inledning", title: "Inledning", deckId: "manovrering_inledning" },
        { id: "manovrering_bat_med_roder", title: "Båt med roder", deckId: "manovrering_bat_med_roder" },
        { id: "manovrering_bat_utan_roder", title: "Båt utan roder", deckId: "manovrering_bat_utan_roder" },
        { id: "manovrering_hog_fart", title: "Hög fart", deckId: "manovrering_hog_fart" },
        { id: "manovrering_fortoja", title: "Förtöja", deckId: "manovrering_fortoja" },
        { id: "manovrering_kasta_loss", title: "Kasta loss", deckId: "manovrering_kasta_loss" },
        { id: "manovrering_segelbat", title: "Segelbåt", deckId: "manovrering_segelbat" },
         {
      id: "manovrering_quiz",
      title: "Kapitelquiz",
      quizId: "manovrering_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "navigationsinstrument",
      title: "Instrument & Utrustning",
      titleShort: "Utrustning",
      children: [
        { id: "navigationsinstrument_kompass", title: "Kompass", deckId: "navigationsinstrument_kompass" },
        { id: "navigationsinstrument_logg", title: "Logg", deckId: "navigationsinstrument_logg" },
        { id: "navigationsinstrument_ekolod", title: "Ekolod", deckId: "navigationsinstrument_ekolod" },
        { id: "navigationsinstrument_satellit", title: "Satellit", deckId: "navigationsinstrument_satellit" },
        { id: "navigationsinstrument_navigator", title: "Navigator", deckId: "navigationsinstrument_navigator" },
        { id: "navigationsinstrument_instrumentkontroll", title: "Instrumentkontroll", deckId: "navigationsinstrument_instrumentkontroll" },
        {
      id: "navigationsinstrument_quiz",
      title: "Kapitelquiz",
      quizId: "navigationsinstrument_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "sjomanskap",
      title: "Båtvett & Ombordkunskap",
      titleShort: "Vett",
      children: [
        { id: "sjomanskap_hansyn_hjalpsamhet", title: "Hänsyn & hjälpsamhet", deckId: "sjomanskap_hansyn_hjalpsamhet" },
        { id: "knopar_och_linor", title: "Knopar och linor", deckId: "knopar_och_linor" },
        { id: "sjomanskap_sjovardighet", title: "Sjövärdighet", deckId: "sjomanskap_sjovardighet" },
        { id: "sjomanskap_ankring", title: "Ankring", deckId: "sjomanskap_ankring" },
        { id: "sjomanskap_kontroller_underhall", title: "Kontroller & underhåll", deckId: "sjomanskap_kontroller_underhall" },
        { id: "sjomanskap_kladsel", title: "Klädsel", deckId: "sjomanskap_kladsel" },
        { id: "sjomanskap_sjofylleri", title: "Sjöfylleri", deckId: "sjomanskap_sjofylleri" },
        { id: "sjomanskap_flaggor", title: "Flaggor", deckId: "sjomanskap_flaggor" },
        { id: "sjomanskap_stabilitet", title: "Stabilitet", deckId: "sjomanskap_stabilitet" },
         {
      id: "sjomanskap_quiz",
      title: "Kapitelquiz",
      quizId: "sjomanskap_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "signalering",
      title: "Kommunikation till Sjöss",
      titleShort: "Signaler",
      children: [
        { id: "signalering_nodsignaler", title: "Nödsignaler", deckId: "signalering_nodsignaler" },
        { id: "signalering_dagersignaler", title: "Dagersignaler", deckId: "signalering_dagersignaler" },
        { id: "signalering_ljudsignaler", title: "Ljudsignaler", deckId: "signalering_ljudsignaler" },
        { id: "signalering_signalflaggor", title: "Signalflaggor", deckId: "signalering_signalflaggor" },
          {
      id: "signalering_quiz",
      title: "Kapitelquiz",
      quizId: "signalering_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "sakerhet",
      title: "Säkerhet & Beredskap",
      titleShort: "Skydd",
      children: [
        { id: "sakerhet_flytvast", title: "Flytväst", deckId: "sakerhet_flytvast" },
        { id: "sakerhet_nodsituationer", title: "Nödsituationer", deckId: "sakerhet_nodsituationer" },
        { id: "sakerhet_sakerhetsutrustning", title: "Säkerhetsutrustning", deckId: "sakerhet_sakerhetsutrustning" },
        { id: "sakerhet_nodutrustning", title: "Nödutrustning", deckId: "sakerhet_nodutrustning" },
        { id: "sakerhet_elsakerhet", title: "Elsäkerhet", deckId: "sakerhet_elsakerhet" },
        { id: "sakerhet_bransle", title: "Bränsle", deckId: "sakerhet_bransle" },
        { id: "sakerhet_sjoraddning", title: "Sjöräddning", deckId: "sakerhet_sjoraddning" },
        { id: "sakerhet_ansvar_skyldigheter", title: "Ansvar & skyldigheter", deckId: "sakerhet_ansvar_skyldigheter" },
         {
      id: "sakerhet_quiz",
      title: "Kapitelquiz",
      quizId: "sakerhet_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "sjukvard",
      title: "Första Hjälpen Ombord",
      titleShort: "Vård",
      children: [
        { id: "sjukvard_grundlaggande", title: "Grundläggande", deckId: "sjukvard_grundlaggande" },
        { id: "sjukvard_sjosjuka", title: "Sjösjuka", deckId: "sjukvard_sjosjuka" },
        { id: "sjukvard_nedkylning", title: "Nedkylning", deckId: "sjukvard_nedkylning" },
        { id: "sjukvard_brannskador", title: "Brännskador", deckId: "sjukvard_brannskador" },
         {
      id: "sjukvard_quiz",
      title: "Kapitelquiz",
      quizId: "sjukvard_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "vader",
      title: "Meteorologi för båtfolk",
      titleShort: "Väder",
      children: [
        { id: "vader_meteorologi", title: "Meteorologi", deckId: "vader_meteorologi" },
        { id: "vader_vaderprognoser", title: "Väderprognoser", deckId: "vader_vaderprognoser" },
        { id: "vader_vind_och_vagor", title: "Vind och vågor", deckId: "vader_vind_och_vagor" },
        { id: "vader_risker", title: "Risker", deckId: "vader_risker" },
        {
      id: "vader_quiz",
      title: "Kapitelquiz",
      quizId: "vader_quiz",
      type: "quiz",
    },
      ],
    },
    {
      id: "miljo",
      title: "Natur och ansvar",
      titleShort: "Natur",
      children: [
        { id: "miljo_miljovett", title: "Miljövett", deckId: "miljo_miljovett" },
        { id: "miljo_bottenfarg", title: "Bottenfärg", deckId: "miljo_bottenfarg" },
        { id: "miljo_toaletter", title: "Toaletter", deckId: "miljo_toaletter" },
        { id: "miljo_eco_driving", title: "Eco-driving", deckId: "miljo_eco_driving" },
        { id: "miljo_allemansratten", title: "Allemansrätten", deckId: "miljo_allemansratten" },
        { id: "miljo_skyddsomraden", title: "Skyddsområden", deckId: "miljo_skyddsomraden" },
         {
            id: "miljo_quiz",
            title: "Kapitelquiz",
            quizId: "miljo_quiz",
            type: "quiz",
          },
    
      ],
    },


    {
      id: "bonus",
      title: "Bonus",
      children: [
        { id: "bonus_flaggor", title: "Flaggor", deckId: "bonus_flaggor" },
      { id: "bonus_dagersignaler", title: "Dagersignaler", deckId: "bonus_dagersignaler" },
      { id: "bonus_sjomarken", title: "Sjömärken", deckId: "bonus_sjomarken" },
      { id: "bonus_symboler", title: "Symboler", deckId: "bonus_symboler" },
      { id: "bonus_lanternor", title: "Lanternor", deckId: "bonus_lanternor" },
      { id: "bonus_fart_distans_tid", title: "Fart Distans Tid", deckId: "bonus_fart_distans_tid" },
      { id: "bonus_ljudsignaler", title: "Ljudsignaler", deckId: "bonus_ljudsignaler" },
       { id: "bonus_fortojningslinor", title: "Förtöjningslinor", deckId: "bonus_fortojningslinor" },
      { id: "bonus_kursberakning", title: "Kursberäkning", deckId: "bonus_kursberakning" },
      { id: "bonus_navigator", title: "Navigator", deckId: "bonus_navigator" },
      { id: "bonus_kardinal", title: "Kardinalmärken", deckId: "bonus_kardinal" },
     
      ],
    },
    ];