import type { FlashCard } from "../../constants/flashcards/types";

import {
    avdriftStrom,
    berakningar,
    bonusDagersignaler,
    bonusFartDistansTid,
    bonusFlaggor,
    bonusFortojningslinor,
    bonusKardinal,
    bonusKursberakning,
    bonusLanternor,
    bonusLjudsignaler,
    bonusNavigator,
    bonusSjomarken,
    bonusSymboler,
    deviationMissvisning,
    distans,
    elektroniskaSjokort,
    farledsnavigation,
    fastaSjomarken,
    flytandeSjomarken,
    instrumentnavigation,
    knoparOchLinor,
    krysspejling,
    kursBaringRiktning,
    laggaUtKurs,
    lanternorFartyg,
    lanternorInledning,
    lanternorMotorbatar,
    lanternorSarskildaFartyg,
    lanternorSegelbatar,
    lanternorSmabatar,
    longitudLatitud,
    manovreringBatMedRoder,
    manovreringBatUtanRoder,
    manovreringFortoja,
    manovreringHogFart,
    manovreringInledning,
    manovreringKastaLoss,
    manovreringSegelbat,
    markeraPosition,
    mataKortDistans,
    mataLangreDistans,
    mataUppKurs,
    miljoAllemansratten,
    miljoBottenfarg,
    miljoEcoDriving,
    miljoMiljovett,
    miljoSkyddsomraden,
    miljoToaletter,
    navigationsbestick,
    navigationsinstrumentEkolod,
    navigationsinstrumentInstrumentkontroll,
    navigationsinstrumentKompass,
    navigationsinstrumentLogg,
    navigationsinstrumentNavigator,
    navigationsinstrumentSatellit,
    navigatornavigation,
    optiskNavigation,
    papperssjokort,
    planering,
    position,
    rattaSattaKurs,
    sakerhetAnsvarSkyldigheter,
    sakerhetBransle,
    sakerhetElsakerhet,
    sakerhetFlytvast,
    sakerhetNodsituationer,
    sakerhetNodutrustning,
    sakerhetSakerhetsutrustning,
    sakerhetSjoraddning,
    signaleringDagersignaler,
    signaleringLjudsignaler,
    signaleringNodsignaler,
    signaleringSignalflaggor,
    sjokortstyper,
    sjomanskapAnkring,
    sjomanskapFlaggor,
    sjomanskapHansynHjalpsamhet,
    sjomanskapKladsel,
    sjomanskapKontrollerUnderhall,
    sjomanskapSjofylleri,
    sjomanskapSjovardighet,
    sjomanskapStabilitet,
    sjukvardBrannskador,
    sjukvardGrundlaggande,
    sjukvardNedkylning,
    sjukvardSjosjuka,
    symboler,
    taFramPosition,
    tillforlitlighet,
    vaderMeteorologi,
    vaderRisker,
    vaderstreck,
    vaderVaderprognoser,
    vaderVindOchVagor,
    vajningsreglerFartyg,
    vajningsreglerInledning,
    vajningsreglerMotorbatar,
    vajningsreglerSegelbatar,
    vajningsreglerSmabatar,
} from "./index";

export const forarintygDecks: Record<string, FlashCard[]> = {
  longitud_latitud: longitudLatitud,
  sjokortstyper,
  papperssjokort,
  elektroniska_sjokort: elektroniskaSjokort,
  symboler,
  flytande_sjomarken: flytandeSjomarken,
  fasta_sjomarken: fastaSjomarken,
  tillforlitlighet,

  vaderstreck,
  navigationsbestick,
  kurs_baring_riktning: kursBaringRiktning,
  position,
  distans,
  berakningar,
  deviation_missvisning: deviationMissvisning,
  avdrift_strom: avdriftStrom,
  ratta_satta_kurs: rattaSattaKurs,

  mata_kort_distans: mataKortDistans,
  mata_langre_distans: mataLangreDistans,
  ta_fram_position: taFramPosition,
  markera_position: markeraPosition,
  lagga_ut_kurs: laggaUtKurs,
  mata_upp_kurs: mataUppKurs,
  krysspejling,

  planering,
  farledsnavigation,
  optisk_navigation: optiskNavigation,
  instrumentnavigation,
  navigatornavigation,

  vajningsregler_inledning: vajningsreglerInledning,
  vajningsregler_smabatar: vajningsreglerSmabatar,
  vajningsregler_segelbatar: vajningsreglerSegelbatar,
  vajningsregler_motorbatar: vajningsreglerMotorbatar,
  vajningsregler_fartyg: vajningsreglerFartyg,

  lanternor_inledning: lanternorInledning,
  lanternor_smabatar: lanternorSmabatar,
  lanternor_segelbatar: lanternorSegelbatar,
  lanternor_motorbatar: lanternorMotorbatar,
  lanternor_fartyg: lanternorFartyg,
  lanternor_sarskilda_fartyg: lanternorSarskildaFartyg,

  manovrering_inledning: manovreringInledning,
  manovrering_bat_med_roder: manovreringBatMedRoder,
  manovrering_bat_utan_roder: manovreringBatUtanRoder,
  manovrering_hog_fart: manovreringHogFart,
  manovrering_fortoja: manovreringFortoja,
  manovrering_kasta_loss: manovreringKastaLoss,
  manovrering_segelbat: manovreringSegelbat,

  navigationsinstrument_kompass: navigationsinstrumentKompass,
  navigationsinstrument_logg: navigationsinstrumentLogg,
  navigationsinstrument_navigator: navigationsinstrumentNavigator,
  navigationsinstrument_satellit: navigationsinstrumentSatellit,
  navigationsinstrument_ekolod: navigationsinstrumentEkolod,
  navigationsinstrument_instrumentkontroll:
    navigationsinstrumentInstrumentkontroll,

  sjomanskap_hansyn_hjalpsamhet: sjomanskapHansynHjalpsamhet,
  knopar_och_linor: knoparOchLinor,
  sjomanskap_sjovardighet: sjomanskapSjovardighet,
  sjomanskap_ankring: sjomanskapAnkring,
  sjomanskap_kontroller_underhall: sjomanskapKontrollerUnderhall,
  sjomanskap_kladsel: sjomanskapKladsel,
  sjomanskap_sjofylleri: sjomanskapSjofylleri,
  sjomanskap_flaggor: sjomanskapFlaggor,
  sjomanskap_stabilitet: sjomanskapStabilitet,

  signalering_nodsignaler: signaleringNodsignaler,
  signalering_dagersignaler: signaleringDagersignaler,
  signalering_ljudsignaler: signaleringLjudsignaler,
  signalering_signalflaggor: signaleringSignalflaggor,

  sakerhet_flytvast: sakerhetFlytvast,
  sakerhet_nodsituationer: sakerhetNodsituationer,
  sakerhet_sakerhetsutrustning: sakerhetSakerhetsutrustning,
  sakerhet_nodutrustning: sakerhetNodutrustning,
  sakerhet_elsakerhet: sakerhetElsakerhet,
  sakerhet_bransle: sakerhetBransle,
  sakerhet_sjoraddning: sakerhetSjoraddning,
  sakerhet_ansvar_skyldigheter: sakerhetAnsvarSkyldigheter,

  sjukvard_grundlaggande: sjukvardGrundlaggande,
  sjukvard_sjosjuka: sjukvardSjosjuka,
  sjukvard_nedkylning: sjukvardNedkylning,
  sjukvard_brannskador: sjukvardBrannskador,

  vader_meteorologi: vaderMeteorologi,
  vader_vaderprognoser: vaderVaderprognoser,
  vader_vind_och_vagor: vaderVindOchVagor,
  vader_risker: vaderRisker,

  miljo_miljovett: miljoMiljovett,
  miljo_bottenfarg: miljoBottenfarg,
  miljo_toaletter: miljoToaletter,
  miljo_eco_driving: miljoEcoDriving,
  miljo_allemansratten: miljoAllemansratten,
  miljo_skyddsomraden: miljoSkyddsomraden,

  bonus_flaggor: bonusFlaggor,
  bonus_dagersignaler: bonusDagersignaler,
  bonus_sjomarken: bonusSjomarken,
  bonus_symboler: bonusSymboler,
  bonus_lanternor: bonusLanternor,
  bonus_fart_distans_tid: bonusFartDistansTid,
  bonus_ljudsignaler: bonusLjudsignaler,
  bonus_fortojningslinor: bonusFortojningslinor,
  bonus_kursberakning: bonusKursberakning,
  bonus_navigator: bonusNavigator,
  bonus_kardinal: bonusKardinal,
};